name: Build - Windows

on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '0 0 * * *'

jobs:
  call-workflow:
    uses: Silverlan/pragma/.github/workflows/build-module.yml@main
    if: github.repository != 'Silverlan/pr_module_template'
    with:
      repository: 'Silverlan/pr_source'
      branch: 'master'
      os: windows
      build-args: '--module pr_mount_external --access-token-fgd=BUILD_TOKEN1'
      tag: ${{ github.event_name == 'schedule' ? 'latest' : '' }}
    secrets:
      repository_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      build_token1: ${{ secrets.UTIL_FGD_TOKEN }}
    permissions:
      contents: write
